
package com.grupobancolombia.intf.producto.depositos.consultacuentadepositos.enlace.v1;

import javax.xml.ws.WebFault;
import com.grupobancolombia.intf.producto.depositos.consultacuentadepositos.v2.ConsultaCuentaDepositosBusinessException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "consultaCuentaDepositosBusinessException", targetNamespace = "http://grupobancolombia.com/intf/Producto/Depositos/ConsultaCuentaDepositos/V2.0")
public class ConsultaCuentaDepositosBusinessExceptionMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ConsultaCuentaDepositosBusinessException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ConsultaCuentaDepositosBusinessExceptionMsg(String message, ConsultaCuentaDepositosBusinessException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ConsultaCuentaDepositosBusinessExceptionMsg(String message, ConsultaCuentaDepositosBusinessException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.grupobancolombia.intf.producto.depositos.consultacuentadepositos.v2.ConsultaCuentaDepositosBusinessException
     */
    public ConsultaCuentaDepositosBusinessException getFaultInfo() {
        return faultInfo;
    }

}
