
package com.grupobancolombia.intf.producto.depositos.consultacuentadepositos.enlace.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaCuentaDepositos", targetNamespace = "http://grupobancolombia.com/intf/Producto/Depositos/ConsultaCuentaDepositos/Enlace/V1.0", wsdlLocation = "file:/C:/xml/wsdl/ConsultaCuentaDepositos_V1.0.wsdl")
public class ConsultaCuentaDepositos_Service
    extends Service
{

    private final static URL CONSULTACUENTADEPOSITOS_WSDL_LOCATION;
    private final static WebServiceException CONSULTACUENTADEPOSITOS_EXCEPTION;
    private final static QName CONSULTACUENTADEPOSITOS_QNAME = new QName("http://grupobancolombia.com/intf/Producto/Depositos/ConsultaCuentaDepositos/Enlace/V1.0", "ConsultaCuentaDepositos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/xml/wsdl/ConsultaCuentaDepositos_V1.0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTACUENTADEPOSITOS_WSDL_LOCATION = url;
        CONSULTACUENTADEPOSITOS_EXCEPTION = e;
    }

    public ConsultaCuentaDepositos_Service() {
        super(__getWsdlLocation(), CONSULTACUENTADEPOSITOS_QNAME);
    }

    public ConsultaCuentaDepositos_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTACUENTADEPOSITOS_QNAME, features);
    }

    public ConsultaCuentaDepositos_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTACUENTADEPOSITOS_QNAME);
    }

    public ConsultaCuentaDepositos_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTACUENTADEPOSITOS_QNAME, features);
    }

    public ConsultaCuentaDepositos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaCuentaDepositos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaCuentaDepositos
     */
    @WebEndpoint(name = "ConsultaCuentaDepositosHttpPort")
    public ConsultaCuentaDepositos getConsultaCuentaDepositosHttpPort() {
        return super.getPort(new QName("http://grupobancolombia.com/intf/Producto/Depositos/ConsultaCuentaDepositos/Enlace/V1.0", "ConsultaCuentaDepositosHttpPort"), ConsultaCuentaDepositos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaCuentaDepositos
     */
    @WebEndpoint(name = "ConsultaCuentaDepositosHttpPort")
    public ConsultaCuentaDepositos getConsultaCuentaDepositosHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://grupobancolombia.com/intf/Producto/Depositos/ConsultaCuentaDepositos/Enlace/V1.0", "ConsultaCuentaDepositosHttpPort"), ConsultaCuentaDepositos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTACUENTADEPOSITOS_EXCEPTION!= null) {
            throw CONSULTACUENTADEPOSITOS_EXCEPTION;
        }
        return CONSULTACUENTADEPOSITOS_WSDL_LOCATION;
    }

}
